export type Product = {
  slug: string;
  name: string;
  category: string;
  price: number;
  unit: string;
  image: string;
  short: string;
  description: string;
  features: string[];
  defaultSize?: string;
  hasCustomSize?: boolean;
};

type Cat = "Outdoor" | "Signage" | "Cards" | "Awards" | "Stickers" | "Print" | "Display";

const imageForProduct = (slug: string) => `/shop-products/${slug}.jpg`;

const make = (
  category: Cat,
  name: string,
  price: number,
  unit: string,
  short: string,
  description: string,
  features: string[],
  opts: { defaultSize?: string; hasCustomSize?: boolean } = {},
): Product => {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  const image = PRODUCT_IMAGES[slug] ?? FALLBACK[category];
  return {
    slug,
    name,
    category,
    price,
    unit,
    image,
    short,
    description,
    features,
    ...opts,
  };
};

export const products: Product[] = [
  // ─────────── OUTDOOR ───────────
  make(
    "Outdoor",
    "Flex Banner Printing",
    12,
    "sq ft",
    "HD flex banners with vivid colors and weatherproof finish.",
    "Premium 440 GSM flex with HD 1440 DPI printing — perfect for shop boards, hoardings and outdoor advertising.",
    ["HD 1440 DPI print", "Weather & UV resistant", "Eyelets included", "Same-day printing"],
    { hasCustomSize: true, defaultSize: "6 x 4 ft" },
  ),
  make(
    "Outdoor",
    "Vinyl Banner",
    18,
    "sq ft",
    "Premium vinyl banners with rich color depth and tear resistance.",
    "Heavy-duty 13oz vinyl banners ideal for long-term outdoor branding and storefront displays.",
    ["Tear-resistant vinyl", "Vivid CMYK print", "Hemmed edges", "Indoor/outdoor use"],
    { hasCustomSize: true, defaultSize: "8 x 4 ft" },
  ),
  make(
    "Outdoor",
    "Mesh Banner",
    22,
    "sq ft",
    "Wind-resistant mesh banners — perfect for tall buildings & fences.",
    "Perforated mesh material allows wind to pass through — ideal for high-rise hoardings and construction sites.",
    ["Wind-permeable mesh", "Anti-tear", "UV stable inks", "Custom grommets"],
    { hasCustomSize: true, defaultSize: "10 x 6 ft" },
  ),
  make(
    "Outdoor",
    "Backlit Flex",
    35,
    "sq ft",
    "Translucent backlit flex for glowing illuminated signs.",
    "Premium backlit flex designed for light-box signage — bright, even illumination day and night.",
    ["Translucent base", "Even light diffusion", "Fade resistant", "Light-box ready"],
    { hasCustomSize: true, defaultSize: "6 x 3 ft" },
  ),
  make(
    "Outdoor",
    "Eco Solvent Prints",
    28,
    "sq ft",
    "Eco-friendly solvent prints with photographic quality.",
    "Low-odor eco solvent printing on premium media — ideal for indoor-outdoor graphics and vehicle wraps.",
    ["Eco-friendly inks", "Photo-quality output", "Scratch resistant", "Indoor safe"],
    { hasCustomSize: true, defaultSize: "4 x 3 ft" },
  ),
  make(
    "Outdoor",
    "Large Hoardings",
    14,
    "sq ft",
    "Massive hoardings for highways, malls and event branding.",
    "Heavy-duty hoarding flex with reinforced stitching and grommets for billboard installations.",
    ["Up to 40 ft", "Reinforced edges", "All-weather", "Installation support"],
    { hasCustomSize: true, defaultSize: "20 x 10 ft" },
  ),
  make(
    "Outdoor",
    "Event Banners",
    16,
    "sq ft",
    "Custom event banners for weddings, parties and corporate gigs.",
    "Vibrant printed banners for stage backdrops, welcome arches and event décor.",
    ["Vivid color print", "Same-day delivery", "Custom shapes", "Eyelets included"],
    { hasCustomSize: true, defaultSize: "8 x 4 ft" },
  ),

  // ─────────── SIGNAGE ───────────
  make(
    "Signage",
    "LED Glow Sign Board",
    450,
    "sq ft",
    "Bright LED signage that turns heads — day and night.",
    "Custom LED glow sign boards with branded acrylic, ACP backing and high-output SMD LEDs.",
    ["3D / acrylic letters", "5-year LED warranty", "Energy efficient SMD", "Installation included"],
    { hasCustomSize: true, defaultSize: "8 x 3 ft" },
  ),
  make(
    "Signage",
    "Glow Sign Board",
    380,
    "sq ft",
    "Classic glow sign boards with backlit illumination.",
    "Traditional flex-faced glow sign boards with internal CFL/LED lighting — economical and bright.",
    ["Backlit flex face", "Aluminium frame", "Energy efficient", "Long lifespan"],
    { hasCustomSize: true, defaultSize: "6 x 3 ft" },
  ),
  make(
    "Signage",
    "Acrylic Signage",
    550,
    "sq ft",
    "Premium acrylic signage with crystal-clear finish.",
    "Laser-cut acrylic signage in any color and thickness — modern, elegant and weather-resistant.",
    ["Laser-cut precision", "Multiple thickness", "Glossy finish", "Mounting hardware"],
    { hasCustomSize: true, defaultSize: "4 x 2 ft" },
  ),
  make(
    "Signage",
    "3D Letter Boards",
    650,
    "sq ft",
    "Eye-catching 3D letter signs in metal & acrylic.",
    "Custom 3D fabricated letter signage with depth and dimension — stainless steel, brass or acrylic.",
    ["3D fabricated letters", "SS / brass / acrylic", "LED backlit option", "Premium finish"],
    { hasCustomSize: true, defaultSize: "Per letter" },
  ),
  make(
    "Signage",
    "Metal Sign Boards",
    480,
    "sq ft",
    "Durable metal sign boards for industrial & commercial use.",
    "Powder-coated metal signage with engraved or printed graphics — built to last decades.",
    ["Powder-coated finish", "Rust resistant", "Engraved graphics", "Heavy-duty"],
    { hasCustomSize: true, defaultSize: "4 x 3 ft" },
  ),
  make(
    "Signage",
    "Direction Boards",
    320,
    "sq ft",
    "Wayfinding & direction boards for offices, malls & parking.",
    "Professional directional signage in ACP, acrylic or metal with crisp typography.",
    ["ACP / acrylic / metal", "Crisp typography", "Wall or pole mount", "Custom layouts"],
    { hasCustomSize: true, defaultSize: "3 x 2 ft" },
  ),
  make(
    "Signage",
    "Designer Name Plates",
    250,
    "piece",
    "Brass, steel & acrylic name plates for home & office.",
    "Elegant engraved name plates in brass, stainless steel, wood and acrylic — for residences, cabins and clinics.",
    ["Multiple materials", "Custom typography", "Mounting hardware", "Long-lasting finish"],
    { hasCustomSize: true, defaultSize: "12 x 4 inch" },
  ),

  // ─────────── CARDS ───────────
  make(
    "Cards",
    "School ID Cards",
    35,
    "piece",
    "Durable PVC school ID cards with photo & lanyard.",
    "Professional double-sided school ID cards with student photo, barcode and free lanyard.",
    ["CR80 standard size", "Double-sided print", "Free lanyard", "Bulk discounts"],
  ),
  make(
    "Cards",
    "Corporate ID Cards",
    50,
    "piece",
    "Premium corporate ID cards with magnetic strip option.",
    "High-end PVC ID cards for offices and enterprises — with optional barcode, QR or magnetic strip.",
    ["Premium PVC", "QR / barcode option", "Magnetic strip available", "Lanyard included"],
  ),
  make(
    "Cards",
    "PVC Cards",
    40,
    "piece",
    "Plain & printed PVC cards in CR80 standard size.",
    "Versatile blank or printed PVC cards for membership, gift cards and access passes.",
    ["CR80 standard", "Glossy / matte", "Bulk pricing", "Same-day printing"],
  ),
  make(
    "Cards",
    "Smart Cards",
    120,
    "piece",
    "RFID & NFC smart cards for access control.",
    "Programmable RFID/NFC cards for office access, attendance and contactless payments.",
    ["RFID / NFC chip", "Custom branding", "Programming support", "High security"],
  ),
  make(
    "Cards",
    "Visitor Cards",
    30,
    "piece",
    "Reusable visitor passes with neck strap.",
    "Durable PVC visitor cards with clear pouch and lanyard — perfect for offices and factories.",
    ["Reusable design", "Clear pouch", "Neck lanyard", "Custom print"],
  ),
  make(
    "Cards",
    "Premium Business Cards",
    3,
    "piece",
    "Luxe matte, spot UV and foil-stamped business cards.",
    "Make a memorable first impression with thick 350 GSM cards. Options for spot UV, foil stamping and rounded corners.",
    ["350 GSM stock", "Spot UV / foil", "Round corners", "Min 100 pcs"],
  ),

  // ─────────── AWARDS ───────────
  make(
    "Awards",
    "Trophy Designs",
    350,
    "piece",
    "Classic metal & resin trophies for sports & events.",
    "Bespoke trophies for sports, schools and corporate ceremonies — with custom engraving and velvet box.",
    ["Custom engraving", "Multiple sizes", "Velvet box packaging", "Bulk orders welcome"],
  ),
  make(
    "Awards",
    "Acrylic Awards",
    550,
    "piece",
    "Modern acrylic awards with sleek transparent finish.",
    "Premium laser-cut acrylic awards with UV-printed graphics — corporate-grade quality.",
    ["Laser-cut acrylic", "UV print graphics", "Crystal-clear finish", "Gift box included"],
  ),
  make(
    "Awards",
    "Wooden Awards",
    650,
    "piece",
    "Classic wooden plaques with metal engraving plates.",
    "Premium teak/rosewood plaques with brass or aluminium engraved plates — timeless and elegant.",
    ["Premium hardwood", "Engraved metal plate", "Velvet backing", "Custom shapes"],
  ),
  make(
    "Awards",
    "Crystal Trophies",
    1200,
    "piece",
    "Luxurious crystal trophies for special recognitions.",
    "K9 optical crystal trophies with 3D laser engraving — the ultimate corporate award.",
    ["K9 optical crystal", "3D laser engraving", "Premium gift box", "Heavy weight feel"],
  ),
  make(
    "Awards",
    "Custom Engraved Awards",
    750,
    "piece",
    "Fully custom awards engraved to your design.",
    "Design your own awards in metal, wood, acrylic or crystal with custom shapes and engravings.",
    ["Fully customizable", "Any material", "Logo engraving", "Design support"],
  ),

  // ─────────── STICKERS ───────────
  make(
    "Stickers",
    "Custom Stickers",
    8,
    "piece",
    "Die-cut custom stickers in any shape or quantity.",
    "Premium glossy/matte vinyl stickers with precise die-cut shapes — branding, packaging and labels.",
    ["Glossy / matte finish", "Custom die-cut", "Waterproof vinyl", "Min order 50 pcs"],
    { hasCustomSize: true, defaultSize: "3 x 3 inch" },
  ),
  make(
    "Stickers",
    "Vinyl Stickers",
    10,
    "piece",
    "Premium vinyl stickers with long-lasting adhesive.",
    "Durable cast vinyl stickers — fade-resistant, waterproof and ideal for outdoor use.",
    ["Cast vinyl", "5-year outdoor life", "Strong adhesive", "Custom shapes"],
    { hasCustomSize: true, defaultSize: "4 x 4 inch" },
  ),
  make(
    "Stickers",
    "Logo Stickers",
    6,
    "piece",
    "Branded logo stickers for products & packaging.",
    "Get your logo printed as professional die-cut stickers in bulk — perfect for product branding.",
    ["Bulk pricing", "Die-cut to logo", "Premium vinyl", "Min 100 pcs"],
    { hasCustomSize: true, defaultSize: "2 x 2 inch" },
  ),
  make(
    "Stickers",
    "Waterproof Stickers",
    12,
    "piece",
    "100% waterproof stickers for bottles, bikes & laptops.",
    "Fully waterproof and dishwasher-safe vinyl stickers — perfect for bottles, vehicles and outdoor gear.",
    ["100% waterproof", "Dishwasher safe", "Scratch resistant", "Vivid colors"],
    { hasCustomSize: true, defaultSize: "3 x 3 inch" },
  ),

  // ─────────── PRINT ───────────
  make(
    "Print",
    "Posters",
    15,
    "piece",
    "High-resolution posters in A4 to A1 sizes.",
    "Sharp 300 DPI prints on premium 170-300 GSM art paper — matte, glossy or laminated.",
    ["A4, A3, A2, A1 sizes", "Glossy / matte paper", "Lamination available", "Fast turnaround"],
    { hasCustomSize: true, defaultSize: "A3" },
  ),
  make(
    "Print",
    "Brochures",
    25,
    "piece",
    "Tri-fold and bi-fold brochures on premium paper.",
    "Professional brochures with crisp folds on 170 GSM art paper — perfect for company profiles.",
    ["Tri-fold / bi-fold", "170 GSM art paper", "Glossy / matte", "Min 100 pcs"],
    { hasCustomSize: true, defaultSize: "A4 tri-fold" },
  ),
  make(
    "Print",
    "Flyers",
    5,
    "piece",
    "Cost-effective flyers for promotions & marketing.",
    "Single-sided or double-sided flyers on 130-170 GSM paper — perfect for mass distribution.",
    ["Single / double-sided", "130-170 GSM", "Bulk discounts", "Same-day printing"],
    { hasCustomSize: true, defaultSize: "A5" },
  ),
  make(
    "Print",
    "Visiting Cards",
    2,
    "piece",
    "Standard visiting cards in matte, glossy & textured.",
    "Crisp 300 GSM visiting cards with options for matte, glossy and textured finishes.",
    ["300 GSM cardstock", "Matte / glossy", "Min 100 pcs", "Same-day printing"],
  ),

  // ─────────── DISPLAY ───────────
  make(
    "Display",
    "Roll-Up Standee",
    950,
    "piece",
    "Portable 6x3 ft roll-up standees with carry bag.",
    "Lightweight roll-up standees with sturdy aluminium base and printed flex panel.",
    ["6 x 3 ft standard", "Carry bag included", "Replaceable graphic", "Quick setup"],
  ),
  make(
    "Display",
    "Exhibition Stands",
    8500,
    "piece",
    "Custom exhibition booth stands & promotional displays.",
    "Modular exhibition stands with branded panels — perfect for trade shows and product launches.",
    ["Modular design", "Reusable frame", "Branded panels", "Easy assembly"],
    { hasCustomSize: true, defaultSize: "10 x 8 ft" },
  ),
  make(
    "Display",
    "Backdrop Displays",
    3500,
    "piece",
    "Step-and-repeat backdrops for events & photo booths.",
    "Professional fabric or flex backdrops with adjustable frames — perfect for media walls and events.",
    ["Adjustable frame", "Wrinkle-free fabric option", "Carry case", "Custom branding"],
    { hasCustomSize: true, defaultSize: "8 x 8 ft" },
  ),
  make(
    "Display",
    "Pop-Up Display",
    6500,
    "piece",
    "Curved pop-up displays for trade shows.",
    "Lightweight curved pop-up display with magnetic graphics — sets up in under 5 minutes.",
    ["Magnetic graphics", "5-min setup", "Hard travel case", "Reusable"],
    { hasCustomSize: true, defaultSize: "8 x 7 ft" },
  ),
];

export const getProduct = (slug: string) => products.find((p) => p.slug === slug);
